backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    collections:
    - label: "Shows"
      name: "shows"
      folder: "_posts/shows"
      create: true
      fields:
        - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
        - {label: "Title", name: "title", widget: "string", tagname: "h1"}
        - {label: "Text", name: "text", widget: "string"}
      - label: "Credits"
        name: "credits"
        folder: "_posts/credits"
        create: true
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Text", name: "text", widget: "string"}
