backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - label: "Credits" # Used in the UI, ie.: "New Post"
    name: "credits" # Used in routes, ie.: /admin/collections/:slug/edit
    folder: "_posts/credits"
    identifier_field: credit
    filter: {field: "Credit", name: "credit", widget: "string"}
    sort: "date:asc" # Default is title:asc
    create: false # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{minute}}-{{second}}-{{slug}}"
    fields:
      - { label: "Credit", name: "credit", widget: "text" }
  - label: "Logo"
    name: "logo"
    folder: "_posts/logo"
    identifier_field: logo
    filter: { field: "Logo", name: "logo", widget: "image" }
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{minute}}-{{second}}-{{slug}}"
    fields:
      - { label: "Logo", name: "logo", widget: "image" }
  - label: "Main Image"
    name: "mainImage"
    folder: "_posts/mainImage"
    identifier_field: mainImage
    filter: { field: "Main Image", name: "mainImage", widget: "image" }
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{minute}}-{{second}}-{{slug}}"
    fields:
      - { label: "Main Image", name: "mainImage", widget: "image" }
  - label: "Menu Video"
    name: "menuVideo"
    folder: "_posts/menuVideo"
    identifier_field: menuVideo
    filter: { field: "Menu Video", name: "menuVideo", widget: "string" }
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{minute}}-{{second}}-{{slug}}"
    fields:
      - { label: "Vimeo Video ID", name: "menuVideo", widget: "string" }
  - label: "Links"
    name: "links"
    files:
      - label: "Menu Links"
        name: "menuLinks"
        file: "_data/links.yml"
        fields:
          - label: "Links List"
            label_singular: "Link"
            name: linksList
            widget: list
            fields:
              - { label: "Link Title", name: "linkTitle", widget: "string" }
              - { label: "Link Url", name: "linkUrl", widget: "string" }
