backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

media_folder: "img/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - label: "Credits" # Used in the UI, ie.: "New Post"
    name: "credits" # Used in routes, ie.: /admin/collections/:slug/edit
    folder: "_posts/credits"
    identifier_field: credit
    filter: {field: "Credit", name: "credit", widget: "string"}
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Credit", name: "credit", widget: "string"}
  - label: "Shows"
    name: "shows"
    folder: "_posts/shows"
    identifier_field: show
    filter: {field: "Show", name: "show", widget: "string"}
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Show", name: "show", widget: "string"}
  - label: "Main Video"
    name: "mainVideo"
    folder: "_posts/mainVideo"
    identifier_field: mainVideo
    filter: {field: "Main Video", name: "mainVideo", widget: "string"}
    sort: "date:desc"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Main Video", name: "mainVideo", widget: "string"}
